query getUser($id: String!) {
    getUser(id: $id) {
        id
        displayName
        city
        state
        gender
        phoneNumber
        email
        experienceOrder
        notifications {
            text
        }
        breakdown {
            ageRange
            gender
            unions
            ethnicity
            vocalRange
        }
        profilePicture {
            s3Key
            url
        }
        profileImages {
            s3Key
            url
        }
    }
}
