export enum ORG_ACTIONS {
    FETCH_ALL_ORGANIZATION_SUCCESS = 'FETCH_ALL_ORGANIZATION_SUCCESS',
    FETCH_ORGANIZATION_SUCCESS = 'FETCH_ORGANIZATION_SUCCESS',
    FETCH_ORGANIZATION_CREATE_SUCCESS = 'FETCH_ORGANIZATION_CREATE_SUCCESS',
    FETCH_ORGANIZATION_EDIT_SUCCESS = 'FETCH_ORGANIZATION_EDIT_SUCCESS',
    FETCH_ORGANIZATION_DELETE_SUCCESS = 'FETCH_ORGANIZATION_DELETE_SUCCESS',
}
