query getRole($roleId: String!) {
    getRole(roleId: $roleId) {
        id
        characterName
        characterSummary
        movementRequirements
        collateral {
            key
            url
        }
    }
}
