query getAudition($auditionId: String!){
    getAudition(auditionId: $auditionId){
        id
        name
        questions {
            id
            text
        }
        timeSlots {
            id
            startTime
            endTime
            talent {
                callBack
                decision
                hasConflicts
                id
                registered
                status
                user {
                    id
                    displayName
                }
            }
        }
        forRoles {
            id
            characterName
        }
        talent {
            id
            decision
            user {
                id
            }
        }
    }
}
