query getOrganizationsForUser {
    getAllOrganizationsForUser {
        owned {
            id
            name
            address
        }
        member {
            id
            name
            address
        }
    }
}
