query getOrganization($orgId: String!){
    getOneOrganization(organizationId: $orgId) {
        id
        name
        owner {
            displayName
        }
        members {
            id
            displayName
        }
    }
}
