export enum ROLE_ACTIONS {
  FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS',
  FETCH_ROLE_CREATE_SUCCESS = 'FETCH_ROLE_CREATE_SUCCESS',
  FETCH_ROLE_EDIT_SUCCESS = 'FETCH_ROLE_EDIT_SUCCESS',
  FETCH_ROLE_DELETE_SUCCESS = 'FETCH_ROLE_DELETE_SUCCESS',
}