export enum AUDITION_ACTIONS {
    ADD_TALENT_TO_AUDITION_SUCCESS = 'ADD_TALENT_TO_AUDITION_SUCCESS',
    FETCH_AUDITION_SUCCESS = 'FETCH_AUDITION_SUCCESS',
    FETCH_AUDITION_CREATE_SUCCESS = 'FETCH_AUDITION_CREATE_SUCCESS',
    FETCH_AUDITION_EDIT_SUCCESS = 'FETCH_AUDITION_EDIT_SUCCESS',
    FETCH_AUDITION_DELETE_SUCCESS = 'FETCH_AUDITION_DELETE_SUCCESS',
    CREATE_AUDITION_TIMESLOT_SUCCESS = 'CREATE_AUDITION_TIMESLOT_SUCCESS',
    FETCH_AUDITION_TIMESLOTS_SUCCESS = 'FETCH_AUDITION_TIMESLOTS_SUCCESS'
}
