query getProjects($organizationId: String!){
    getAllProjects(organizationId: $organizationId) {
        id
        name
        director
        summary
        notes
        rehearsalDateStart
        rehearsalDateEnd
        performanceDateStart
        performanceDateEnd
        auditions {
            id
            name
        }
    }
}
