query searchForAuditions($query: String!){
    searchForAuditions(query: $query) {
        id
        name
        auditionType
        address
        forRoles {
            characterName
            characterSummary
            breakdown {
                ageRange
                gender
                unions
                ethnicity
                vocalRange
            }
        }
    }
}
